// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  fen: __t.string(),
  turn: __t.string(),
  status: __t.string(),
  winner: __t.i8(),
  legalMoves: __t.string().name("legal_moves"),
  lastMove: __t.string().name("last_move"),
  check: __t.bool(),
  clocked: __t.bool(),
  whiteMs: __t.i64().name("white_ms"),
  blackMs: __t.i64().name("black_ms"),
  incMs: __t.i64().name("inc_ms"),
  turnStartMicros: __t.u64().name("turn_start_micros"),
});
