// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  identity: __t.identity(),
  slot: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  facing: __t.i8(),
  hp: __t.f32(),
  phase: __t.string(),
  phaseFrame: __t.u32().name("phase_frame"),
  attackKind: __t.string().name("attack_kind"),
  attackHasHit: __t.bool().name("attack_has_hit"),
  stunFrames: __t.u32().name("stun_frames"),
  prevJump: __t.bool().name("prev_jump"),
  prevLight: __t.bool().name("prev_light"),
  prevHeavy: __t.bool().name("prev_heavy"),
  prevMoveX: __t.i8().name("prev_move_x"),
  dashTapDir: __t.i8().name("dash_tap_dir"),
  dashTapFrames: __t.u32().name("dash_tap_frames"),
});
