// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  status: __t.string(),
  phase: __t.string(),
  round: __t.u32(),
  roundWins0: __t.u32().name("round_wins_0"),
  roundWins1: __t.u32().name("round_wins_1"),
  pendingWinner: __t.i8().name("pending_winner"),
  tick: __t.u64(),
  endsAtMicros: __t.u64().name("ends_at_micros"),
  phaseEndsAtMicros: __t.u64().name("phase_ends_at_micros"),
});
