// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  status: __t.string(),
  phase: __t.string(),
  currentSeat: __t.u8().name("current_seat"),
  seatCount: __t.u8().name("seat_count"),
  die1: __t.u8().name("die_1"),
  die2: __t.u8().name("die_2"),
  doublesThisTurn: __t.u8().name("doubles_this_turn"),
  pendingSpace: __t.i8().name("pending_space"),
  winnerSeat: __t.i8().name("winner_seat"),
  log: __t.string(),
});
