// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  status: __t.string(),
  phase: __t.string(),
  currentSeat: __t.u8().name("current_seat"),
  seatCount: __t.u8().name("seat_count"),
  group0: __t.string().name("group_0"),
  group1: __t.string().name("group_1"),
  winnerSeat: __t.i8().name("winner_seat"),
  ballInHand: __t.bool().name("ball_in_hand"),
  log: __t.string(),
  firstContact: __t.string().name("first_contact"),
  pottedRed: __t.u8().name("potted_red"),
  pottedYellow: __t.u8().name("potted_yellow"),
  pottedBlack: __t.bool().name("potted_black"),
  cueScratched: __t.bool().name("cue_scratched"),
  shotTicks: __t.u32().name("shot_ticks"),
});
