// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChessGame = __t.object("ChessGame", {
  roomId: __t.u64(),
  fen: __t.string(),
  turn: __t.string(),
  status: __t.string(),
  winner: __t.i8(),
  legalMoves: __t.string(),
  lastMove: __t.string(),
  check: __t.bool(),
  clocked: __t.bool(),
  whiteMs: __t.i64(),
  blackMs: __t.i64(),
  incMs: __t.i64(),
  turnStartMicros: __t.u64(),
});
export type ChessGame = __Infer<typeof ChessGame>;

export const FightEvent = __t.object("FightEvent", {
  roomId: __t.u64(),
  kind: __t.string(),
  victimSlot: __t.i8(),
  x: __t.f32(),
  y: __t.f32(),
  amount: __t.f32(),
});
export type FightEvent = __Infer<typeof FightEvent>;

export const FightInput = __t.object("FightInput", {
  identity: __t.identity(),
  roomId: __t.u64(),
  moveX: __t.i8(),
  jump: __t.bool(),
  light: __t.bool(),
  heavy: __t.bool(),
  block: __t.bool(),
  crouch: __t.bool(),
  seq: __t.u32(),
});
export type FightInput = __Infer<typeof FightInput>;

export const FightMatch = __t.object("FightMatch", {
  roomId: __t.u64(),
  status: __t.string(),
  phase: __t.string(),
  round: __t.u32(),
  roundWins0: __t.u32(),
  roundWins1: __t.u32(),
  pendingWinner: __t.i8(),
  tick: __t.u64(),
  endsAtMicros: __t.u64(),
  phaseEndsAtMicros: __t.u64(),
  roundSeconds: __t.i32(),
  maxHp: __t.i32(),
  maxStamina: __t.f32(),
  staminaOn: __t.bool(),
  staminaName: __t.string(),
  roundsToWin: __t.i32(),
  maxRounds: __t.i32(),
});
export type FightMatch = __Infer<typeof FightMatch>;

export const FightTick = __t.object("FightTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.u64(),
});
export type FightTick = __Infer<typeof FightTick>;

export const Fighter = __t.object("Fighter", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  slot: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  facing: __t.i8(),
  hp: __t.f32(),
  phase: __t.string(),
  phaseFrame: __t.u32(),
  attackKind: __t.string(),
  attackHasHit: __t.bool(),
  airAttackUsed: __t.bool(),
  stunFrames: __t.u32(),
  stamina: __t.f32(),
  staminaCd: __t.u32(),
  exhausted: __t.bool(),
  attackCd: __t.u32(),
  prevJump: __t.bool(),
  prevLight: __t.bool(),
  prevHeavy: __t.bool(),
  prevMoveX: __t.i8(),
  dashTapDir: __t.i8(),
  dashTapFrames: __t.u32(),
});
export type Fighter = __Infer<typeof Fighter>;

export const GameRoom = __t.object("GameRoom", {
  id: __t.u64(),
  gameId: __t.string(),
  status: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  settings: __t.string(),
});
export type GameRoom = __Infer<typeof GameRoom>;

export const MonopolyGame = __t.object("MonopolyGame", {
  roomId: __t.u64(),
  status: __t.string(),
  phase: __t.string(),
  currentSeat: __t.u8(),
  seatCount: __t.u8(),
  die1: __t.u8(),
  die2: __t.u8(),
  doublesThisTurn: __t.u8(),
  pendingSpace: __t.i8(),
  winnerSeat: __t.i8(),
  log: __t.string(),
});
export type MonopolyGame = __Infer<typeof MonopolyGame>;

export const MonopolyPlayer = __t.object("MonopolyPlayer", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  seat: __t.u8(),
  vanStyle: __t.u8(),
  cash: __t.i32(),
  position: __t.u8(),
  inJail: __t.bool(),
  jailTurns: __t.u8(),
  getOutCards: __t.u8(),
  bankrupt: __t.bool(),
});
export type MonopolyPlayer = __Infer<typeof MonopolyPlayer>;

export const MonopolyProperty = __t.object("MonopolyProperty", {
  id: __t.u64(),
  roomId: __t.u64(),
  spaceIdx: __t.u8(),
  ownerSeat: __t.i8(),
  houses: __t.u8(),
  mortgaged: __t.bool(),
});
export type MonopolyProperty = __Infer<typeof MonopolyProperty>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  displayName: __t.string(),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
  location: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const PoolBall = __t.object("PoolBall", {
  id: __t.u64(),
  roomId: __t.u64(),
  num: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  pocketed: __t.bool(),
});
export type PoolBall = __Infer<typeof PoolBall>;

export const PoolGame = __t.object("PoolGame", {
  roomId: __t.u64(),
  status: __t.string(),
  phase: __t.string(),
  currentSeat: __t.u8(),
  seatCount: __t.u8(),
  group0: __t.string(),
  group1: __t.string(),
  winnerSeat: __t.i8(),
  ballInHand: __t.bool(),
  log: __t.string(),
  firstContact: __t.string(),
  pottedRed: __t.u8(),
  pottedYellow: __t.u8(),
  pottedBlack: __t.bool(),
  cueScratched: __t.bool(),
  shotTicks: __t.u32(),
});
export type PoolGame = __Infer<typeof PoolGame>;

export const PoolSeat = __t.object("PoolSeat", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  seat: __t.u8(),
});
export type PoolSeat = __Infer<typeof PoolSeat>;

export const PoolTick = __t.object("PoolTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.u64(),
});
export type PoolTick = __Infer<typeof PoolTick>;

export const RoomMember = __t.object("RoomMember", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  slot: __t.u8(),
});
export type RoomMember = __Infer<typeof RoomMember>;

